name: Docker Compose Actions Workflow
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
      - feat/move-to-gh-actions # Remove this after development
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the resume
        run: docker-compose up
      with: 
        env: 
          GH_TOKEN: ${{ secrets.github_token }}