name: Docker Compose Actions Workflow
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
      - main
      - 'feat/move-to-gh-actions' # Remove this after development
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Build the resume
        run: docker-compose up
        env: 
          GH_TOKEN: ${{ secrets.github_token }}