name: Docker Compose Actions Workflow
on: push
  branches:
    - master
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the resume
        run: docker-compose up
      with: 
        env: 
          GH_TOKEN: ${{ secrets.github_token }}