name: Render Resume
on: 
  push:
    branches:
    - master
    - main
jobs:
  render-resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the resume
        run: docker compose up
      - name: Push to GH Pages
        run: ./push.sh
        env: 
          GH_TOKEN: ${{ secrets.github_token }}
